export const BULK_ACTIONS = {
  NEXT: 'NEXT',
  NEXT_LOAD: 'NEXT_LOAD',
  CLOSE: 'CLOSE',
  CLOSE_RELOAD: 'CLOSE_RELOAD',
  BACK: 'BACK',
  PREV_LOAD: 'PREV_LOAD',
  SHOW_ERROR: 'SHOW_ERROR',
  CONFIRM_OK: 'CONFIRM_OK',
  RELOAD_STATE: 'RELOAD_STATE',
  CANCEL: 'CANCEL',
  TOGGLE_CONFIRM: 'TOGGLE_CONFIRM',
};
