export const DEFAULT_API_CLEAR_TIME = 5 * 60 * 1000;
export const MAX_API_CLEAR_TIME = 60 * 60 * 1000;
export const SEARCH_KEYS = {
  ACTOR_TYPE: 'ACTOR_TYPE',
  BRAND: 'BRAND',
  CATEGORY: 'CATEGORY',
  CHANNELS: 'CHANNELS',
  COLLABORATOR_TYPES: 'COLLABORATOR_TYPES',
  COLLABORATOR_USERS: 'COLLABORATOR_USERS',
  LOCATIONS: 'LOCATIONS',
  LOCATION_TYPES: 'LOCATION_TYPES',
  PRODUCERS: 'PRODUCERS',
  PROP: 'PROP',
  SET_UP: 'SET_UP',
  SHOT_CATEGORY: 'SHOT_CATEGORY',
  SHOT_COLOR_LABEL: 'SHOT_COLOR_LABEL',
  STAFF_USERS: 'STAFF_USERS',
  TENANT: 'TENANT',
};
