import { PERMISSIONS_FEATURES_KEYS } from "../../../common/permission";

export const NOTIFICATION_TYPES = {
  SHOT_COMMENT: 'SHOT_COMMENT',
  CONTENT_REQUEST_COMMENT: 'CONTENT_REQUEST_COMMENT',
  MARKUP_COMMENT: 'MARKUP_COMMENT',
  EDITED_CONTENT: 'EDITED_CONTENT',
};

export const NAVIGATION_STACK_TYPE = {
  SCROLL: 'SCROLL',
  INTERNAL_REDIRECTION: 'INTERNAL_REDIRECTION',
  ACTION: 'ACTION',
};

export const NAVIGATION_ACTION_TYPE = {
  OPEN_LIGHT_BOX: 'OPEN_LIGHT_BOX',
  OPEN_EDIT_WIDGET: 'OPEN_EDIT_WIDGET',
};

export const NOTIFICATION_FEATURES_MAP = {
  [NOTIFICATION_TYPES.CONTENT_REQUEST_COMMENT]: [
    PERMISSIONS_FEATURES_KEYS.FULL_ACCESS_CONTENT_REQUEST_LIST,
    PERMISSIONS_FEATURES_KEYS.READ_ACCESS_CONTENT_REQUEST_LIST,
    PERMISSIONS_FEATURES_KEYS.FULL_ACCESS_COMMENTS,
  ],
  [NOTIFICATION_TYPES.SHOT_COMMENT]: [
    PERMISSIONS_FEATURES_KEYS.FULL_ACCESS_SHOT_LIST,
    PERMISSIONS_FEATURES_KEYS.READ_ACCESS_SHOT_LIST,
    PERMISSIONS_FEATURES_KEYS.FULL_ACCESS_COMMENTS,
  ],
  [NOTIFICATION_TYPES.MARKUP_COMMENT]: [
    PERMISSIONS_FEATURES_KEYS.FULL_ACCESS_SHOT_LIST,
    PERMISSIONS_FEATURES_KEYS.READ_ACCESS_SHOT_LIST,
    PERMISSIONS_FEATURES_KEYS.FULL_ACCESS_SHOT_CONTENTS,
    PERMISSIONS_FEATURES_KEYS.FULL_ACCESS_CONTENTS_LIGHT_BOX,
  ],
  [NOTIFICATION_TYPES.EDITED_CONTENT]: [
    PERMISSIONS_FEATURES_KEYS.FULL_ACCESS_SHOT_LIST,
    PERMISSIONS_FEATURES_KEYS.READ_ACCESS_SHOT_LIST,
    PERMISSIONS_FEATURES_KEYS.FULL_ACCESS_SHOT_CONTENTS,
  ],
};
export const NOTIFICATION_FEATURE_UNIQUE_KEY_MAP = {
  1: [
    PERMISSIONS_FEATURES_KEYS.FULL_ACCESS_SHOT_LIST,
    PERMISSIONS_FEATURES_KEYS.READ_ACCESS_SHOT_LIST
  ],
  2: [
    PERMISSIONS_FEATURES_KEYS.FULL_ACCESS_CONTENT_REQUEST_LIST,
    PERMISSIONS_FEATURES_KEYS.READ_ACCESS_CONTENT_REQUEST_LIST
  ],
  3: [PERMISSIONS_FEATURES_KEYS.FULL_ACCESS_COMMENTS],
  4: [PERMISSIONS_FEATURES_KEYS.FULL_ACCESS_SHOT_CONTENTS],
  5: [PERMISSIONS_FEATURES_KEYS.FULL_ACCESS_CONTENTS_LIGHT_BOX],
};
