// Unified Shot Statuses
export const SHOT_STATUS = {
  BACKLOG: 'BACKLOG',
  PRODUCT_PENDING: 'PRODUCT_PENDING',
  CREATIVE: 'CREATIVE',
  CREATIVE_REVIEW: 'CREATIVE_REVIEW',
  BUNDLING: 'BUNDLING',
  SCHEDULED: 'SCHEDULED',
  PHOTOSHOOT: 'PHOTOSHOOT',
  CAPTURED: 'CAPTURED',
  SELECTION: 'SELECTION',
  EDITING: 'EDITING',
  REVIEW: 'REVIEW',
  SPILLED: 'SPILLED',
  DONE: 'DONE',
};
export const SHOT_STATUS_NEXT_MAP = {
  [SHOT_STATUS.BACKLOG]: null,
  [SHOT_STATUS.PRODUCT_PENDING]: null,
  [SHOT_STATUS.CREATIVE]: null,
  [SHOT_STATUS.CREATIVE_REVIEW]: null,
  [SHOT_STATUS.BUNDLING]: null,
  [SHOT_STATUS.SCHEDULED]: SHOT_STATUS.CAPTURED,
  [SHOT_STATUS.PHOTOSHOOT]: SHOT_STATUS.CAPTURED,
  [SHOT_STATUS.CAPTURED]: null,
  [SHOT_STATUS.EDITING]: null,
  [SHOT_STATUS.REVIEW]: null,
  [SHOT_STATUS.DONE]: null,
};
